# Default values for weyundong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-vpc.cn-chengdu.aliyuncs.com/buf/nginx
  pullPolicy: IfNotPresent
  tag: "1.25.1-alpine-slim"

imagePullSecrets: ["aliyun"]
nameOverride: "www-dindinle-com"
fullnameOverride: "www-dindinle-com"
restartPolicy: Always

volumes:
- name: html
  hostPath:
    path: /home/jensen/deploy/www.dindinle.com/data
    type: DirectoryOrCreate

volumeMounts:
- name: html
  mountPath: /usr/share/nginx/html 

secret:
  data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdBekNDQk91Z0F3SUJBZ0lRRDgxTGZrZEEvYUVGRitkeFFMNVFjREFOQmdrcWhraUc5dzBCQVFzRkFEQnUKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1TMHdLd1lEVlFRREV5UkZibU55ZVhCMGFXOXVJRVYyWlhKNWQyaGxjbVVnClJGWWdWRXhUSUVOQklDMGdSekV3SGhjTk1qTXdOakUxTURBd01EQXdXaGNOTWpRd05qRTBNak0xT1RVNVdqQWIKTVJrd0Z3WURWUVFERXhCM2QzY3VaR2x1WkdsdWJHVXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdmNmV0F2eStVZWpnM2M0UkhQZnA3MlBIRTd3TS9Pbm12ZHdBNk1aNFdFSkt5ckc4CnlqRXpiWExmYjRtKytVeFE1U3BwVzJtc0VPWXhiZnNkUjJUUWhyakNZVDQ4U2VxdlBEWUt2RENMWG1SSktoZisKMlU2U2lVbHduaksybTZJcDkySDh0a1F3cHFiYkpwMjBydXNhS0lpUVkvY2twZVVyekd5UFFLb0xnTmtVWmkvdQpMajJ4bUNmcDBkQlJGZ0ErQmFWZ0xDOVExbW1WY0x2UEs3ejR6WTQybEZXUGs3R2ZsSDFzbEJSQytldE5KK2xzCmlISVlXMmIyTG5ldk9rTFFwK3RGOHh3MTBzSHkyQnYzNzR1TzduYmpFcS9QbzFWU20vejNaUmNqb3lrd1U1Zk0KN21kNjViUjVTdnppc3dBRitlV0lxUlhYbDZnRHRYU3BUTktWcndJREFRQUJvNElDN2pDQ0F1b3dId1lEVlIwagpCQmd3Rm9BVVZYUlBzbkpQOVdDNlVOSFg1bEZjbWdHSEd0Y3dIUVlEVlIwT0JCWUVGR2R1ajI1ME9kSVJzSUsyCmJ6cU1ZK0FtYmxqMk1Da0dBMVVkRVFRaU1DQ0NFSGQzZHk1a2FXNWthVzVzWlM1amIyMkNER1JwYm1ScGJteGwKTG1OdmJUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRgpCd01DTUQ0R0ExVWRJQVEzTURVd013WUdaNEVNQVFJQk1Da3dKd1lJS3dZQkJRVUhBZ0VXRzJoMGRIQTZMeTkzCmQzY3VaR2xuYVdObGNuUXVZMjl0TDBOUVV6Q0JnQVlJS3dZQkJRVUhBUUVFZERCeU1DUUdDQ3NHQVFVRkJ6QUIKaGhob2RIUndPaTh2YjJOemNDNWthV2RwWTJWeWRDNWpiMjB3U2dZSUt3WUJCUVVITUFLR1BtaDBkSEE2THk5agpZV05sY25SekxtUnBaMmxqWlhKMExtTnZiUzlGYm1OeWVYQjBhVzl1UlhabGNubDNhR1Z5WlVSV1ZFeFRRMEV0ClJ6RXVZM0owTUFrR0ExVWRFd1FDTUFBd2dnRitCZ29yQmdFRUFkWjVBZ1FDQklJQmJnU0NBV29CYUFCMkFIYi8KaUQ4S3R2dVZVY0poelBXSHVqUzBwTTI3S2R4b1FncWY1bWRNV2pwMEFBQUJpTDROOUJFQUFBUURBRWN3UlFJZwpiTFVQcWVwY1cxTThaUDBDSlZyN2prUVptVk16Mm53c1ZiYzM0MmdFMUhNQ0lRQ1Nac0k1cUN0YlJEREJDdFNZCklscm9tNTVsZWp0dXJCcFBITUFJSnh6Q1JnQjJBRWl3NDJ2YXBrYzBEK1ZxQXZxZE1Pc2NVZ0hMVnQwc2dkbTcKdjZzNTJJUnpBQUFCaUw0TjlBa0FBQVFEQUVjd1JRSWhBUFIwWjBxaEpYeHhxMFJYbWtBemc2MUh2TzdmQjRDQwpsTmxzQ2gyeTllYU5BaUJXRGF0UjM3S01od0xpZk40ZGZIbFplcEx1Unk2Q3ZPRmtPUENnZ1FKWnhRQjJBTnEyCnYycy90YllpbjV2Q3UxeHI2SENSY1d5N1VZU0ZOTDJrUFRCSTEvdXJBQUFCaUw0Tjg5OEFBQVFEQUVjd1JRSWcKYzNPbjJNZzdnVFhaRWY4TFMwR3Z0c054Z3pZSXpSUkZRK09lSzFCKzd0TUNJUUQ3MjRpNi9WaDZ1OEhwalVjVgpVZDhoczdCUWpYcW9yWG9RN2hTaUJQQUx6akFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBb2RNejNtL3B1eThNCjg2aW1yYTdxMWNTUmpGZldFT1hPT1dLbGVRb09pdEs1RkxFSHRMd0dSVHhtbktBWEhpWCtHWGxMOWxqWkpqUWYKZnRZNmlUaU1jK3JpcjZUdHZYcWxJL0h4Z2VuQTN1VTdtQmFoYmc0SHFrdGxyWEJJSCtYNlVaQzNTNS9KQ1grZwpxUjhITFh5UXBDOVNNTzJUQTU5VzRDbWxlN1hRc3BNWGx0MFdib2NsdzIyVmx6NDNlMml5NlRzY1BWS1FBZklvCnhUdHdvYkRJdDRNcG5FUlJQcXhlZlQ0dno1aklDd2s4Wk5NMkFvQlRyOEFYSVVGN1hwNGtGdWFHQVJJUlFrVWcKRU91NFhLeWxrWENTTEo4bHd2TmEydFV6TmliMGVUY0lOOHRrNHVFUnJjY040ZjdLRHBmNGtoWVFBaUVKazFrSApkZjFSekk3cFp3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRXFqQ0NBNUtnQXdJQkFnSVFBbm1zUll2QnNrV3IrWUJUelN5YnNUQU5CZ2txaGtpRzl3MEJBUXNGQURCaApNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzCmQzY3VaR2xuYVdObGNuUXVZMjl0TVNBd0hnWURWUVFERXhkRWFXZHBRMlZ5ZENCSGJHOWlZV3dnVW05dmRDQkQKUVRBZUZ3MHhOekV4TWpjeE1qUTJNVEJhRncweU56RXhNamN4TWpRMk1UQmFNRzR4Q3pBSkJnTlZCQVlUQWxWVApNUlV3RXdZRFZRUUtFd3hFYVdkcFEyVnlkQ0JKYm1NeEdUQVhCZ05WQkFzVEVIZDNkeTVrYVdkcFkyVnlkQzVqCmIyMHhMVEFyQmdOVkJBTVRKRVZ1WTNKNWNIUnBiMjRnUlhabGNubDNhR1Z5WlNCRVZpQlVURk1nUTBFZ0xTQkgKTVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFBlUDZ3a2FiNDFkeVFoNm1LYwpvSHF0M2pSSXhXNU1EdmY5UXlpT1I3VmZGd0s2NTZlczBVRmlJYjc0TjlwUm50ekYxVWdZekRHdTNwcFpWTWRvCmxieGhtNmRXUzlPSy9sRmVoS05UME9ZSTlhcWs2RitVN2NBNmp4U0MraURCUFh3ZEY0cnMzS1J5cDNhUW42cGoKcHAxeXI3SUI2WTR6djcyRWUvUGxaLzZySzZJbkM2V3BLMG5QVk9ZUjduOWlEdVBlMUU0SXhVTUJIL1QzMyszaAp5dUgzZHZmZ2lXVU9Va2pkcE1ieXhYK1hObGU1dUVJaXlCc2k0SXZiY1RDaDhydWlmQ0lpNW1EWGtacm5NVDhuCndmWUNWNnY2a0RkWGtiZ0dSTEtzUjRwdWNiSnRiS3FJa1VHeHVaSTJ0N3BmZXdLUmM1bldlY3ZEQlpmMytwMU0KcEE4Q0F3RUFBYU9DQVU4d2dnRkxNQjBHQTFVZERnUVdCQlJWZEUreWNrLzFZTHBRMGRmbVVWeWFBWWNhMXpBZgpCZ05WSFNNRUdEQVdnQlFEM2xBMVZ0Rk11MmJ3bytJYkc4T1hzajNSVlRBT0JnTlZIUThCQWY4RUJBTUNBWVl3CkhRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQklHQTFVZEV3RUIvd1FJTUFZQkFmOEMKQVFBd05BWUlLd1lCQlFVSEFRRUVLREFtTUNRR0NDc0dBUVVGQnpBQmhoaG9kSFJ3T2k4dmIyTnpjQzVrYVdkcApZMlZ5ZEM1amIyMHdRZ1lEVlIwZkJEc3dPVEEzb0RXZ000WXhhSFIwY0RvdkwyTnliRE11WkdsbmFXTmxjblF1ClkyOXRMMFJwWjJsRFpYSjBSMnh2WW1Gc1VtOXZkRU5CTG1OeWJEQk1CZ05WSFNBRVJUQkRNRGNHQ1dDR1NBR0cKL1d3QkFqQXFNQ2dHQ0NzR0FRVUZCd0lCRmh4b2RIUndjem92TDNkM2R5NWthV2RwWTJWeWRDNWpiMjB2UTFCVApNQWdHQm1lQkRBRUNBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSzNHcDYvYUdxN2FCWnN4Zi9vUStURC9CClN3VzNBVTRFVEsrR1FmMmtGellaa2J5NVNGckhkUG9tdW54MkhCelZpVWNoR29vZkdnZzdnSFcwVzNNbFFBWFcKTTByNUxVdlN0Y3I4MlFEV1lOUGFVeTR0YUNRbXlhSitWQis2d3hIc3RTaWdPbFNORjJhNnZnNHJnZXhpeGVpVgo0WVNCMDNZcXAydDNUZVpITTlFU2ZrdXM3NG5ReVc3cFJHZXpqK1RDNDR4Q2FnQ1FRT3p6Tm16RUFQMlNuQ3JKCnNORTJEcFJWTW5MOEo2eEJSZGptT3NDM042Y1F1S3VSWGJ6QnlWQmpDcUFBOHQxTDBJKzl3WEplckxQeUVyankKck1LV2FCRkxtZksvQUhORjRaaWh3UEdPYzd3NlVIY3pCWlhINVJGekpObnd3K1duS3VUUEkwSGZuVkg4bGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdmNmV0F2eStVZWpnM2M0UkhQZnA3MlBIRTd3TS9Pbm12ZHdBNk1aNFdFSkt5ckc4CnlqRXpiWExmYjRtKytVeFE1U3BwVzJtc0VPWXhiZnNkUjJUUWhyakNZVDQ4U2VxdlBEWUt2RENMWG1SSktoZisKMlU2U2lVbHduaksybTZJcDkySDh0a1F3cHFiYkpwMjBydXNhS0lpUVkvY2twZVVyekd5UFFLb0xnTmtVWmkvdQpMajJ4bUNmcDBkQlJGZ0ErQmFWZ0xDOVExbW1WY0x2UEs3ejR6WTQybEZXUGs3R2ZsSDFzbEJSQytldE5KK2xzCmlISVlXMmIyTG5ldk9rTFFwK3RGOHh3MTBzSHkyQnYzNzR1TzduYmpFcS9QbzFWU20vejNaUmNqb3lrd1U1Zk0KN21kNjViUjVTdnppc3dBRitlV0lxUlhYbDZnRHRYU3BUTktWcndJREFRQUJBb0lCQUVOcXB2TGV0L2svQWdxcApObGtWRkl4TzVKeDFGQ1FRTDBESTA2WGRRMGtQRzZTUHFTSW1najlpTEU5aUhtNVBGdm1ockZXbDMxTU5nd2V2CnlnSGZwVmdHY0Q2OUxndVFDL29XdEkrUHF5SzMrMm14cG4ycHROS0NQVGhsaVlzVisxUi9BWmY1OTFKc09iT3AKR0ZOKy93YmhKSEh1akoxR0lOMzR2cGJaRVVjT3VkSlMzQnk0a1VpOGVuSFloOURjUVA3VEdOUjhIbWQ3cCszVgpwSURRZDFOYTBPZTlwVFNMUUV0bU4rcHBuS2JvMlpaUkl4aHZMakFINEpMTUJZSE9FNWZ4bGk3ZXZDVHlyZ3JBClMzSXEyZEdSMFNyeWNoSXdiYms4R1dKNDFESDVHMnJSb1BEZ0tZUVl2M21rQ3NVSWYyMzExMGdUVGxJZG5tOVAKcEhjOGl1a0NnWUVBNGhialVzbXh3T09sTm00cDZxRUV4b2c0a20vaFFsclZCWmd2VWEyS0Y3THVhY2k5akJCNwpWSGI3dnp3aUl6c1M0OERJMWlYZU45M3B2WlpMMW1jeExhbVA3ZWtzT2NiL1lzZFYwcndHbm9SSk9iWmZEWGF3CjNPMUdHdmdsQ1B5ZThpck9pWG5vL1RCYU03VkZPMjd5bDVDWC9MQ0RYOVF0cklKSzIySXNldk1DZ1lFQTF1TkIKVWZuNTNqMUZoRGswa29rMjNvVy9mNERDK3E3akxlNXA2aTh1WVdBWWtUT0xkOEFKbGNoV0VDdGlRdTFnRTNkdwpBZmJzUWJSTnoyNXZQK290SDE3Qjc2QTdvR0xSYUZmSWRweDVSYjFqeVliYVE3QzdvL0pkUEcvcGpZU1VySDZ5CnVXSHhUQU9rVXY3c0hIanJNZ1FKZE5CclFGeFRBR1hCWmlBMThWVUNnWUFpUWFtTC83ZUpMSFQ1L0ZNcGsrQXYKWExDRnI2SUg5YzlWRzZ2L3lqV2tSWjVPTlBaVFpLUHJObVFLbzhmZ1lyRUlCVXZvOXEvbTh4N1pkUTVrbkJvZApleFd0ektqQTBHQWR6V281bGZmQ3lQUjNaQ1NlMjU4TXVuN20welo1V0IyVlA5c3ZoV05DQ2JPQkpqUXBQelJPCnRyL3dyNllZUFFQMm9YOUtJbVB1OVFLQmdHSGZCWXdwdDNWU0lNeFZKYTJzRXpLTVppalRZM3E3bHJyL3dIdXAKMjR6OE1KUkpqcmNPM3c2NlBRQ0dVZTI3b2F1Y0ZZYS9pT0Z3RnBSb2J3RUVUbUxnVEtJd0w1Z2dDZEpsVU9jOAo0enN4UkRhd1ZjN0l1dDJ6OEdVcmI0dEdIRlRvSzh5bFlEcEgybHIyd21GQmJaWE5JdVZ5VzdibmxlSXpkajltCllrczFBb0dBU0FhemViVzhkdVJoZ0R4T3NnWXpxM0xadFdXMWliSTlzMTBTQTZBckJhKzI0L3NsMW1YV0JQRXYKaS9tdmdvaUNLd0hFZ2g3MlZhRzNzNXIzVWZTeU5WU2xnNnYrQk9ycVcvTmNIRE1TSWpRRm82RWtYUStpSSthTQo1UTBXbXk4QkhzcTlvZWJwcmhETFpuZjZVSXFhbk1saHBpMjNxcVVTeFNYeHlEeENENzQ9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

service:
  type: ClusterIP
  port: 80

middleware:
  enabled: true
  spec:
    redirectScheme:
      scheme: https
      port: "443"
      permanent: true

ingressroute:
  enabled: true
  specs:
  - name: "www-dindinle-com-http"
    spec:
      entryPoints: 
      - web
      routes:
      - kind: Rule
        match: Host(`www.dindinle.com`)
        middlewares:
        - name: '{{ default "www-dindinle-com" .Values.fullnameOverride }}'
        services:
        - name:  '{{ default "www-dindinle-com" .Values.fullnameOverride }}'
          port: 80
  - name: "www-dindinle-com-https"
    spec:
      entryPoints: 
      - websecure
      tls:
        secretName: '{{ default "www-dindinle-com" .Values.fullnameOverride }}'
      routes:
      - kind: Rule
        match: Host(`www.dindinle.com`)
        services:
        - name:  '{{ default "www-dindinle-com" .Values.fullnameOverride }}'
          port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: 
  kubernetes.io/hostname:
  - k3s002
  - k3s003

tolerations: []

