# Default values for weyundong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-vpc.cn-chengdu.aliyuncs.com/buf/nginx
  pullPolicy: IfNotPresent
  tag: "1.25.1-alpine-slim"

imagePullSecrets: ["aliyun"]
nameOverride: "www-weyundong-com"
fullnameOverride: "www-weyundong-com"
restartPolicy: Always

volumes: {}
# - name: html
#   hostPath:
#     path: /home/jensen/deploy/www.weyundong.com/data
#     type: DirectoryOrCreate

volumeMounts: {}
# - name: html
#   mountPath: /usr/share/nginx/html 

secret:
  enabled: false
  data:

service:
  type: ClusterIP
  port: 80

middleware:
  enabled: false
  # spec:
  #   redirectScheme:
  #     scheme: https
  #     port: "443"
  #     permanent: true

ingressroute:
  enabled: false
  # specs:
  # - name: "www-weyundong-com-http"
  #   spec:
  #     entryPoints: 
  #     - web
  #     routes:
  #     - kind: Rule
  #       match: Host(`www.weyundong.com`)
  #       middlewares:
  #       - name: '{{ default "www-weyundong-com" .Values.fullnameOverride }}'
  #       services:
  #       - name:  '{{ default "www-weyundong-com" .Values.fullnameOverride }}'
  #         port: 80
  # - name: "www-weyundong-com-https"
  #   spec:
  #     entryPoints: 
  #     - websecure
  #     tls:
  #       secretName: '{{ default "www-weyundong-com" .Values.fullnameOverride }}'
  #     routes:
  #     - kind: Rule
  #       match: Host(`www.weyundong.com`)
  #       services:
  #       - name:  '{{ default "www-weyundong-com" .Values.fullnameOverride }}'
  #         port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []