{{- include "common.deployment" (list . "web.deployment") -}}
{{- define "web.deployment" -}}
spec:
  selector:
    matchLabels:
      app: {{ template "common.name" . }}
  replicas: {{ .Values.replicaCount }}    
  template:
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes: {{ toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      containers:
      -
{{ include "common.util.merge" (list . "web.container" "common.container.tpl") | indent 8 }}
{{- end -}}

{{- define "web.container" -}}
envFrom:
- configMapRef:
    name: {{ template "common.fullname" . }}
    optional: true
{{- with .Values.volumeMounts }}  
volumeMounts: {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}